### ISSUE TITLE
Region param is unused in generated endpoint requests?

### ISSUE THREAD

**Issue by monachilada** [vaersaagod/dospaces#12]
It appears to me that the `region` param required in defining a volume is never actually used anywhere in generating the endpoint URL for interacting with my space. On the other hand, if I don't include the region domain segment directly in my endpoint URL, then it won't work.

For better illustration, this is what I'm using in my `.env` file which the volume definition then reads from...

**Works:**
```
ASSETS_ENDPOINT="https://fra1.digitaloceanspaces.com"
ASSETS_REGION="random_string"
```

**Doesn't work:**
```
ASSETS_ENDPOINT="https://digitaloceanspaces.com"
ASSETS_REGION="fra1"
```

**Comment by aelvan** [comment]
You're right, this is something that stems from duplicating the behaviour of the S3 volume, in the case of Spaces, it's not actually used. I'll remove it down the line.
