### ISSUE TITLE
Volume exception when changing asset slug

### ISSUE THREAD

**Issue by j-greig** [vaersaagod/dospaces#14]
Getting an error when changing the slug of an entry whose images are stored in a subfolder named after that slug.

Eg `Couldn’t rename folder-1/image.jpg to folder/image.jpg`

Is this possible? Or should I just remove {slug} from the upload location on the asset field settings?

**Comment by aelvan** [comment]
Not sure I understand the setup, but I tested having {slug} in the upload location for an assets field, and can't produce any errors. But the file stays in the original folder when changing slug, so dunno. Maybe a Craft bug/behaviour that got fixed/changed.

Renaming folders in general in the volume works, so closing this for now.
