### ISSUE TITLE
Weird behaviour when deleting assets

### ISSUE THREAD

**Issue by sunscreem** [vaersaagod/dospaces#19]
Is anyone finding the when they delete an asset in craft, it's removed from the spaces folder but remains in the CDN?

**Comment by sunscreem** [comment]
Hey @aelvan.

I've been working with DO on this one. Trying to work out why item's deleted via the API aren't being removed from the CDN.

Can you tell me what the default Cache-Control TTL is when I leave it blank?

**Comment by aelvan** [comment]
The cache duration is 1209600 seconds (14 days) by default.

Assets not being deleted from the CDN is to be expected, an item in an edge cache should persist unless it's specifically purged. No such purging is implemented in the volume.

**Comment by sunscreem** [comment]
Hey @aelvan.

We had an incident recently where an image needed to be deleted urgently.

It was deleted in craft, but not purged. 

How do we purge it once its been deleted?

**Comment by aelvan** [comment]
See https://www.digitalocean.com/docs/spaces/how-to/manage-cdn-cache/

It would also be possible to make an integration with the DO API, to do this automatically when an asset is deleted in Craft, see https://www.digitalocean.com/community/questions/api-to-purge-file-cache-from-spaces-cdn-after-file-update.

**Comment by sunscreem** [comment]
Thanks @aelvan - appreciated.
