### ISSUE TITLE
Error message upload failed

### ISSUE THREAD

**Issue by klubdev** [vaersaagod/dospaces#2]
Hi, we encounter this error message when we try to upload a new file.
Hope you can help.

Upload failed. The error message was: “Call to undefined method GuzzleHttp\Psr7\Uri::composeComponents()”

![settings-drop-spaces](https://user-images.githubusercontent.com/42821529/47955235-70cad280-df9d-11e8-8fbd-600261688815.jpg)

**Comment by kjbrum** [comment]
@klubdev Have you tried deleting your `vendor` directory and reinstalling composer dependencies?

**Comment by aelvan** [comment]
^
