### ISSUE TITLE
Issue with Indexing Assets

### ISSUE THREAD

**Issue by kerns** [vaersaagod/dospaces#20]
I get the following dialog when attempting to index assets on my Digital Ocean volume, and I'm not sure what to make of it. 

https://user-images.githubusercontent.com/20254/104110281-8737eb80-52d6-11eb-9e60-2f3966a42556.mov

I am able to successfully upload/edit images in these locations on this volume, and I can see them successfully uploaded when browsing via the DO web UI. Any ideas? Presumably based on a problem with @ in folder names, but not sure that Digital Ocean sees it as a problem.

Perhaps an issue more broadly with Craft?

**Comment by kerns** [comment]
I have tried everything I can think of... wondering if it's related to how the files were created, dragging in the UI from an S3 bucket to the newly created DO space. 🤔

**Comment by aelvan** [comment]
I'm seeing the exact same behaviour on both Local volumes and the first-party S3 volume, so yes, it's a Craft issue. 

You should file an issue in the [craftcms/cms](https://github.com/craftcms/cms/issues) repo, closing this.
