### ISSUE TITLE
Plugin/Craft Update: Error when generating bucket Url 

### ISSUE THREAD

**Issue by lucashfreitas** [vaersaagod/dospaces#21]
After updating craft & plugin version, the bucket url is being wrongly generated. For some reason the BUCKET_NAME is being outputted before the HTTP protocol, which is generating an invalid url when uploading assets. I have tested the environment multiple times before and after upgrading the craft/plugin and the error happens as result of the update. All the configuration on the admin asset to be ok. 

I've done a quick investigation/debug on  the `flysystem-aws-s3-v3` - as the plugin uses it under the hood but could not find the root cause it. 

I will do further investigation/debug as we need to reach the function that generates the bucket url (should be located in flysystem library/aws s3 client) and check why the bucket name is being added to the HTTP protocol url.

Please check the screenshot below:

![image](https://user-images.githubusercontent.com/11416392/112245930-c14e4200-8cb6-11eb-838e-955457eeb1c3.png)

- *Plugin Version*: "1.1.2",
- *Craft Version:*: "3.6.10" - The error is also happening on 3.5x version.

Thanks.

**Comment by mmikkel** [comment]
I believe this is an issue in aws-sdk-php, see [this issue](https://github.com/thephpleague/flysystem-aws-s3-v3/issues/250#issuecomment-803580076) (comment)

**Comment by lucashfreitas** [comment]
That's true. I just realized that the error is happening on AWSS3Client/aws-sdk level. Will manually install a stable version from aws-sdk :) Thanks for the quick turnaround @mmikkel !

**Comment by mmikkel** [comment]
No problem @lucashfreitas. I'll close this issue since there's nothing we can do about it on our end.
