### ISSUE TITLE
Support for controlling public/private visibility

### ISSUE THREAD

**Issue by ryanfoote** [vaersaagod/dospaces#3]
Hi! Is there any planned support for controlling the visibility of files on a per-volume basis?

**Comment by qrazi** [comment]
I just dug into it a bit, and it seems that the Public URL-setting of a Volume controls the visibility of assets in that volume.

So, 
<img width="306" alt="image" src="https://user-images.githubusercontent.com/7550540/83411542-c0db7680-a418-11ea-9112-656a1c9a0409.png">

Check:
- `\craft\base\FlysystemVolume::visibility` (https://github.com/craftcms/cms/blob/develop/src/base/FlysystemVolume.php#L344)
- https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L645

I haven't actually verified this yet, but please report back if you do! :)

**Comment by qrazi** [comment]
I just verified this. I think the docs could be updated with this. I'll try to make time for a PR.

Set the volume to not have public URLs. Upload some files. Check them out in the Spaces environment. See their visibility is "private". Copy/paste the "origin" and "edge" (if CDN enabled) URLs and try them. You will see an access denied message.
