### ISSUE TITLE
Upload failed. The error message was: “Endpoints must be full URIs and include a scheme and host”

### ISSUE THREAD

**Issue by toddpadwick** [vaersaagod/dospaces#4]
Trying to set up spaces but I can't seem to get it to work. I have the following .env variables set up:

```
SPACES_API_KEY="XXXXXXXXXXXXXXX"

SPACES_SECRET="XXXXXXXXXXXXXXX"

SPACES_ENDPOINT="https://sfo2.digitaloceanspaces.com"

SPACES_REGION="sfo2"

SPACES_BUCKET="test"

SPACES_URL="https://test.sfo2.digitaloceanspaces.com"
```

I then have the following alias' setup:

```
'aliases' => [

            '@spacesUrl' => getenv('SPACES_URL'),

            '@spacesKey' => getenv('SPACES_API_KEY'),

            '@spacesSecret' => getenv('SPACES_SECRET'),

            '@spacesEndpoint' => getenv('SPACES_ENDPOINT'),

            '@spacesRegion' => getenv('SPACES_REGION'),

            '@spacesBucket' => getenv('SPACES_BUCKET'),

        ],
```

and finally here is a screenshot of my volume set up:

![image](https://user-images.githubusercontent.com/36191462/51830794-8fb0da80-22e8-11e9-8385-136af146457e.png)

Im new to using a CDN for assets so I've probably made an obvious mistake but any help would be really appreciated :)

**Comment by benjaminleonard** [comment]
I had the same error – until I added this (with the correct handle) to volumes.php
Not sure why it has to be duplicated across the asset fields, and volumes.php – or which value it prioritises.

`
return [
    'mySpacesVolumeHandle' => [
        'hasUrls' => true,
        'url' => 'https://my-spaces-bucket.ams3.digitaloceanspaces.com/',
        'keyId' => getenv('SPACES_API_KEY'),
        'secret' => getenv('SPACES_SECRET'),
        'endpoint' => getenv('SPACES_ENDPOINT'),
        'region' => getenv('SPACES_REGION'),
        'bucket' => getenv('SPACES_BUCKET'),
    ],
];
`

**Comment by Tam** [comment]
@toddpadwick @benjaminleonard I've added support for aliases and env variables in #5, hopefully it'll be merged soon!

**Comment by aelvan** [comment]
The original error was due to the volume driver not parsing aliases. This has been added in v1.1.0, thanks to @Tam.

**Comment by toddpadwick** [comment]
Ah I see... excellent, thanks @Tam and @aelvan :)
