### ISSUE TITLE
Uploading portrait-oriented images loses their orientation

### ISSUE THREAD

**Issue by robarov** [vaersaagod/dospaces#6]
- Uploading a portrait-oriented image to a DO Spaces volume results in a landcape-oriented image
- The image is taken with a DSLR, so it may be EXIF related
- Uploading the same image to a local asset volume respects the portrait orientation

Craft version 3.1.9

**Comment by aelvan** [comment]
Hi,

I don't think this has anything to do with the volume. Have you tried uploading to a local volume to confirm? 

More likely, you haven't enabled `preserveExifData`, or don't have the EXIF extension installed. See the following links:

https://docs.craftcms.com/v3/config/config-settings.html#preserveexifdata
https://craftcms.stackexchange.com/questions/17945/images-containing-exif-orientation-tag-are-not-rotated-on-upload

**Comment by robarov** [comment]
Yes, uploading the same image to a local volume respects the portrait orientation (=works).
