### ISSUE TITLE
Setting Up with CDN Support

### ISSUE THREAD

**Issue by danleecreates** [vaersaagod/dospaces#9]
Can I clarify how we set this up with the CDN feature? After I noticed images were loading in slowly I began using the following - which loads in images faster. BUT then I noticed that I can no longer upload files through front end forms into volumes set up with Digital Ocean, also some of my templates are not using the full path referencing the cdn... 

    'SPACES_API_KEY' => 'XXXXXXX',
    'SPACES_SECRET' => 'XXXXXXX',
    'SPACES_ENDPOINT' => 'https://ams3.cdn.digitaloceanspaces.com',
    'SPACES_REGION' => 'ams3',
    'SPACES_BUCKET' => 'test',
    'SPACES_URL' => 'https://test.ams3.cdn.digitaloceanspaces.com',

This is the error I get when uploading files through front end forms (bucket name is changed to test).

`Error executing "ListObjects" on "https://test.ams3.cdn.digitaloceanspaces.com/?prefix=content%2Fdocs%2F&delimiter=%2F&encoding-type=url"; AWS HTTP error: Client error: `GET https://test.ams3.cdn.digitaloceanspaces.com/?prefix=content%2Fdocs%2F&delimiter=%2F&encoding-type=url` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><BucketName>test</BucketName><RequestId>tx0000 (truncated...) AccessDenied (client): - <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><BucketName>test</BucketName><RequestId>tx0000000000000199322ec-005cdc1c7b-10e1ef4-ams3a</RequestId><HostId>10e1ef4-ams3a-ams3</HostId></Error>`

**Comment by danleecreates** [comment]
Hi @aelvan I have been in contact with Digital Ocean Support regarding the issue... 

They said:

> The Spaces access keys won't be working for CDN endpoints so you are getting this "AccessDenied" error when uploading files. You have to use the Origin URL "https://ams3.digitaloceanspaces.com" to upload files using Spaces access keys. 

I "Think" this does mean we can't use the Endpoint URL with the CDN string like so "_https://ams3.cdn.digitaloceanspaces.com_"  to server images faster. Is this correct and if so is there a way to fix this?

Thanks
Dan

**Comment by aelvan** [comment]
It means that the endpoint URL is for contacting the API, and that doesn't have anything to do with what the resulting URL for your images will be, and how fast you load. I haven't tested this, but most likely you should do:

```
'SPACES_ENDPOINT' => 'https://ams3.digitaloceanspaces.com',
'SPACES_URL' => 'https://test.ams3.cdn.digitaloceanspaces.com',
```

**Comment by danleecreates** [comment]
Thanks for your reply @aelvan 

Ok so the 'SPACES_URL' should be used to load the image in the browser. Are we sure it isn't using the Endpoint URL value?

With the settings defined as you reccomend, we noticed that some pages are not using the cdn string in the image url. See [example page here](https://staging.123innovation.co.uk/news/cpi-collaborates-on-cutting-edge-testing-facility-to-advance-formulated-liquid-manufacturing). 

But on other pages it is working without issue and the cdn string IS in the URL. See [example page](https://staging.123innovation.co.uk/case-studies/stream-bio). 

Any idea what could be the issue?

Here is our settings for the volume.
![Screen Shot 2019-05-30 at 10 36 30](https://user-images.githubusercontent.com/7198242/58623925-ecd49100-82c6-11e9-9263-44efad6e2382.png)

**Comment by aelvan** [comment]
Doesn't make much sense. You sure there isn't some kind of caching going on here? Are you using template caching or some kind of frontside cache?

**Comment by DavidOliver** [comment]
I just enabled the CDN by adding `.cdn` to the `Base URL` field in the storage settings, and all seems well: uploads in the control panel are still working and the URLs of assets in the frontend pages have the `.cdn` in them.

![Screenshot from 2020-03-06 22-32-18](https://user-images.githubusercontent.com/192853/76124167-65a50e00-5ffa-11ea-926f-11b41f226854.png)

**Comment by estebancastro** [comment]
I had this issue, I solved (at least work for me, upload the images without problems) with this setup:

**.env**
```
SPACES_URL=https://bucket-name.ams3.cdn.digitaloceanspaces.com/
SPACES_API_KEY=MFUU7XQ2NFL7YRRGUVJ1
SPACES_SECRET=De1YF926020n1UL8QyTmgh9n1UL1QyUq5k
SPACES_ENDPOINT=https://ams3.digitaloceanspaces.com
SPACES_REGION=ams3
SPACES_BUCKET=bucket-name
```

**config.php**
```
'@spacesUrl' => App::env('SPACES_URL'),
'@spacesKeyId' => App::env('SPACES_API_KEY'),
'@spacesSecret' => App::env('SPACES_SECRET'),
'@spacesEndpoint' => App::env('SPACES_ENDPOINT'),
'@spacesRegion' => App::env('SPACES_REGION'),
'@spacesBucket' => App::env('SPACES_BUCKET'),
```

**Note:** I think the readme file https://github.com/vaersaagod/dospaces/blob/master/README.md should be updated with https://craftcms.com/docs/3.x/config/#aliases because **config/volumes.php** has been deprecated: https://imgur.com/x7QwmF3

**Comment by aelvan** [comment]
In fact, you should rather use [environmental variables](https://craftcms.com/docs/3.x/config/#environmental-configuration) as that's the new best practice after project config happened.

Closing since the original issue was solved way back when.
